"""document page_count and extraction_method

Revision ID: fdc274667d36
Revises: 5c98794116b3
Create Date: 2026-07-21 09:32:34.626472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc274667d36'
down_revision: Union[str, None] = '5c98794116b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('extraction_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'extraction_method')
    op.drop_column('documents', 'page_count')
    # ### end Alembic commands ###
